all : server encoder

server_objs = ServerSocket.o Socket.o 
nodes_objs = ServerSocket.o ClientSocket.o Socket.o 

server: $(server_objs) server.cpp
	g++ -o server $(server_objs) server.cpp -Wno-deprecated

encoder: $(nodes_objs)  encoder.cpp
	g++ -o encoder $(nodes_objs) encoder.cpp -Wno-deprecated


ServerSocket.o:ServerSocket.cpp
	g++ -c -o ServerSocket.o ServerSocket.cpp

ClientSocket.o:ClientSocket.cpp
	g++ -c -o ClientSocket.o ClientSocket.cpp

Socket.o:Socket.cpp
	g++ -c -o Socket.o Socket.cpp

clean:
	rm -f *.o server encoder ClientSocket ServerSocket Socket
	




