all : robo_eight robo_square

objs = normal.o func.o controls.o

robo_eight: $(objs) robo_eight.cpp
	g++ -o robo_eight $(objs) robo_eight.cpp -Wno-deprecated

robo_square: $(objs) robo_square.cpp
	g++ -o robo_square $(objs) robo_square.cpp -Wno-deprecated

	
controls.o:controls.cpp
	g++ -c -o controls.o controls.cpp -Wno-deprecated

normal.o:normal.c
	gcc -c -o normal.o normal.c

func.o:func.cpp
	g++ -c -o func.o func.cpp -Wno-deprecated


clean:
	rm -f *.o robo_eight robo_square normal func controls
	




